notifications:
  email:
    - ppalant@redhat.com
  on_success: change
  on_failure: always
sudo: required
dist: xenial
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    update: true
    packages:
      - automake
      - autoconf
      - autoconf-archive
      - pkg-config
      - libglib2.0-dev
      - libcacard-dev
before_script:
  - pkg-config --libs libcacard
script:
  - ./autogen.sh && ./configure && make && make distcheck
