notifications:
  email:
    - ppalant@redhat.com
  on_success: change
  on_failure: always
sudo: required
dist: xenial
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    update: true
    packages:
      - automake
      - autoconf
      - autoconf-archive
      - pkg-config
      - libglib2.0-dev
install:
  - git clone https://gitlab.freedesktop.org/spice/libcacard.git
  - cd libcacard && ./autogen.sh && ./configure && make && sudo make install
script:
  - ./autogen.sh && ./configure && make all && make distcheck
